version: '3'

services:
############################## Metrics ##############################
  prometheus:
    image: prom/prometheus:v2.15.2
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
  
  grafana:
    image: grafana/grafana:6.6.0
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/:/etc/grafana

######################################################################
############################## Tracing ###############################

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

######################################################################
############################### Logs #################################

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

###############################################################################
############################## Demo applications ##############################

  app-python:
    build: ./app-python
    environment:
      - JAEGER_HOST=jaeger
      - DEBUG_METRICS=false
    ports:
      - "5000:5000"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"

  app-springboot:
    build: ./app-springboot
    environment:
      - JAEGER_HOST=jaeger
    ports:
      - "8080:8080"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"   

##############################################################################

volumes:
  prometheus_data: {}
  grafana_data: {}