apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: true
  editable: false
- name: Loki
  type: loki
  url: http://loki:3100
  isDefault: false
  editable: false
- name: Jaeger
  type: jaeger
  url: http://jaeger:16686
  isDefault: false
  editable: false