
info:
  app:
    name: app-springboot
    description: Demo opne tracing
    version: 0.0.1

spring:
  application:
    name: app-springboot
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    rest:
      base-path: /api


logging:
  level:
    org.springframework.web: DEBUG
    be.lampiris: DEBUG

management:
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, info, health, env, scheduledtasks
  info:
    git:
      mode: full
      enabled: true
  health:
    diskspace:
      enabled: true



opentracing:
  jaeger:
    udp-sender:
      host: ${JAEGER_HOST:localhost}
      port: 6831
    const-sampler:
      decision: true
